services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thales-produto-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Thales
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: thales-postgres
    environment:
      POSTGRES_DB: Thales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
